# Generated by Django 4.0.2 on 2022-02-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default='sarah', null=True, on_delete=django.db.models.deletion.PROTECT, to='store.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
