# Generated by Django 4.0.2 on 2022-03-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_payment_status_order_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
