# Generated by Django 4.0.2 on 2022-03-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
