# Generated by Django 4.0.2 on 2022-03-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
