# Generated by Django 4.0.2 on 2022-02-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'collection']},
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
    ]
